# Test computed vars
Git repo: testrepo
Git branch: testbranch
Git commit: testhash
Git clean: False
Go arch: amd64

src-root-data
src-daemon-base-data

cr-a-u-root-data

cr-a-u-x-root-data
cr-a-u-x-daemon-base-data

Ubuntu Maintainer "email@ubuntu.email"

xenial