# Test computed vars
Git repo: {{ env['GIT_REPO']}}
Git branch: {{ env['GIT_BRANCH'] }}
Git commit: {{ env['GIT_COMMIT'] }}
Git clean: {{ env['GIT_CLEAN'] }}
Go arch: {{ env['GO_ARCH'] }}

{{ template['src']['root'] }}
{{ template['src']['daemon-base'] }}

{{ template['ceph-releases']['all']['ubuntu']['root'] }}

{{ template['ceph-releases']['all']['ubuntu']['16.04']['root'] }}
{{ template['ceph-releases']['all']['ubuntu']['16.04']['daemon-base'] }}

{{ template['maintainer'] }}

{{ template['os-codename'] }}
