apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rbd-provisioner
  namespace: ceph
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rbd-provisioner
    spec:
      containers:
      - name: rbd-provisioner
        # Currently outdated, hence use inofficial version
        # built from https://github.com/kubernetes-incubator/external-storage
        # (in ceph/rbd subdir)
        # cf. https://github.com/kubernetes-incubator/external-storage/issues/608
        #image: "quay.io/external_storage/rbd-provisioner:latest"
        image: anatolyrugalev/rbd-provisioner:latest
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/rbd
      serviceAccount: rbd-provisioner
      imagePullSecrets:
      - name: regsecret

