# Daemon Dockerfile
Ubuntu Maintainer "email@ubuntu.email"
    xenial
    this
      is
      a
      big
      block && \
    echo 'hi mom'


this
      is
      a
      big
      block

cr-a-u-root-data

cr-a-u-x-root-data

Ubuntu Maintainer "email@ubuntu.email"

src-root-data
src-daemon-data