# Daemon Dockerfile
{{ template['nested'] }}


{{ template['bloc'] }}

{{ template['ceph-releases']['all']['ubuntu']['root'] }}

{{ template['ceph-releases']['all']['ubuntu']['16.04']['root'] }}

{{ template['maintainer'] }}

{{ template['src']['root'] }}
{{ template['src']['daemon'] }}
