name: rhcs
on: [pull_request]
jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compose the RHCS 5 container image
        run: BRANDING=redhat VERSION=5 CEPH_RELEASE=pacific ./contrib/compose-rhcs.sh

      - name: validate description pattern in Dockerfile
        run: grep 'description="Red Hat Ceph Storage 5"' staging/pacific-ubi8-redhat-latest-x86_64/composed/Dockerfile

      - name: compose the RHCS 6 container image
        run: BRANDING=redhat VERSION=6 CEPH_RELEASE=quincy ./contrib/compose-rhcs.sh

      - name: validate description pattern in Dockerfile
        run: grep 'description="Red Hat Ceph Storage 6"' staging/quincy-ubi9-redhat-latest-x86_64/composed/Dockerfile

      - name: compose the RHCS 7 container image
        run: BRANDING=redhat VERSION=7 CEPH_RELEASE=reef ./contrib/compose-rhcs.sh

      - name: validate rhcs 7 description pattern in Dockerfile
        run: grep 'description="Red Hat Ceph Storage 7"' staging/reef-ubi9-redhat-latest-x86_64/composed/Dockerfile

      - name: compose the IBM Ceph 7 container image
        run: BRANDING=ibm VERSION=7 CEPH_RELEASE=reef ./contrib/compose-rhcs.sh

      - name: validate IBM Ceph 7 description pattern in Dockerfile
        run: grep 'description="IBM Storage Ceph 7"' staging/reef-ubi9-ibm-latest-x86_64/composed/Dockerfile

      - name: compose the RHCS 8 container image
        run: BRANDING=redhat VERSION=8 CEPH_RELEASE=squid ./contrib/compose-rhcs.sh

      - name: validate rhcs 8 description pattern in Dockerfile
        run: grep 'description="Red Hat Ceph Storage 8"' staging/squid-ubi9-redhat-latest-x86_64/composed/Dockerfile

      - name: compose the IBM Ceph 8 container image
        run: BRANDING=ibm VERSION=8 CEPH_RELEASE=squid ./contrib/compose-rhcs.sh

      - name: validate ibm ceph 8 description pattern in Dockerfile
        run: grep 'description="IBM Storage Ceph 8"' staging/squid-ubi9-ibm-latest-x86_64/composed/Dockerfile
