---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mgr-prometheus
  namespace: ceph
  labels:
    app: ceph
    daemon: mgr
spec:
  ports:
  - port: 9283
    protocol: TCP
    targetPort: 9283
  selector:
    app: ceph
    daemon: mgr
